// Production Worker against isolated D1/R2. Dispatcher identities are local fixtures only.
import {createRequire} from 'node:module';
import {realpathSync,readdirSync,readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'..'),require=createRequire(realpathSync(root+'/node_modules/wrangler/package.json'));
const {Miniflare}=require('miniflare'),server=root+'/dist/server';
const modules=readdirSync(server,{recursive:true}).filter(p=>p.endsWith('.js')||p.endsWith('.mjs')).sort((a,b)=>a==='index.js'?-1:b==='index.js'?1:a.localeCompare(b)).map(p=>({type:'ESModule',path:server+'/'+p}));
const mf=new Miniflare({modules,modulesRoot:server,compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],cf:false});
const team={id:'operator',email:'sandipl4742@gmail.com'},admin={id:'admin',email:'admin@example.com'},parent={id:'parent-a',email:'parent-a@example.com'},guardian={id:'parent-b',email:'parent-b@example.com'};
let checks=0;const pass=n=>{checks++;console.log('PASS',n)};
async function call(user,path,body){const headers={'oai-authenticated-user-id':user.id,'oai-authenticated-user-email':user.email,Origin:'https://school.test'};if(body)headers['Content-Type']='application/json';const r=await mf.dispatchFetch('https://school.test'+path,{headers,method:body?'POST':'GET',body:body&&JSON.stringify(body)});return {status:r.status,data:await r.json()};}
const view=async(user,role)=>{const r=await call(user,'/api/school?portal=1&role='+role);assert.equal(r.status,200);return r.data.schools};
const ok=r=>{assert.equal(r.status,200,JSON.stringify(r.data));return r.data};
async function action(user,role,id,name,payload={}){const e=(await view(user,role)).find(e=>e.school.id===id);return call(user,'/api/school',{role,schoolId:id,action:name,payload,revision:e?.revision});}
try{
 const db=await mf.getD1Database('DB');for(const file of readdirSync(root+'/drizzle').filter(x=>x.endsWith('.sql')).sort())for(const sql of readFileSync(root+'/drizzle/'+file,'utf8').split('--> statement-breakpoint').filter(x=>x.trim()))await db.prepare(sql.trim()).run();
 ok(await call(team,'/api/school',{action:'seed'}));const demos=await view(team,'platform');const fixtures=[];
 for(const [index,e] of demos.entries()){const raw=await db.prepare('SELECT data FROM schools WHERE id=?').bind(e.school.id).first();const s=JSON.parse(raw.data);s.id='enrollment-school-'+index;s.ownerId='fixture-school-owner';s.adminEmail=admin.email;s.demo=false;s.links=[];s.requests=[];s.invitations=[];fixtures.push(s);await db.prepare('INSERT INTO schools(id,owner_id,data,revision) VALUES(?,?,?,0)').bind(s.id,s.ownerId,JSON.stringify(s)).run();}
 const s=fixtures[0],t=s.students[0];
 assert.equal((await view(parent,'parent')).length,0);assert.equal((await view(team,'platform')).find(e=>e.school.id===s.id).school.students.length,0);pass('platform summaries and unconnected parents reveal no student records');
 const invite=ok(await action(admin,'admin',s.id,'createInvitation',{studentId:t.id,label:'Mother'})).invitation;
 assert.match(invite.code,/^[A-F0-9]{5}(-[A-F0-9]{5}){3}$/);assert(!invite.url.includes(t.id));const adminSchool=(await view(admin,'admin')).find(e=>e.school.id===s.id).school;assert(!JSON.stringify(adminSchool).includes(invite.code.replaceAll('-','')));assert(!adminSchool.invitations[0].hash);pass('private invitation has random code, no child URL details, and no retrievable secret');
 const redeem=(user,i=invite,dob=t.dob)=>action(user,'parent',undefined,'redeemInvitation',{code:i.code,dob,relationship:'Mother'});
 assert.equal((await redeem(parent,invite,'2000-01-01')).status,400);assert.equal((await view(parent,'parent')).length,0);pass('incorrect DOB denies all child access');
 const pair=await Promise.all([redeem(parent),redeem(guardian)]);assert.equal(pair.filter(r=>r.status===200).length,1);const winner=pair[0].status===200?parent:guardian,loser=winner===parent?guardian:parent;assert.equal((await redeem(loser)).status,400);pass('concurrent and subsequent redemptions enforce single use');
 const second=ok(await action(admin,'admin',s.id,'createInvitation',{studentId:t.id,label:'Father'})).invitation;ok(await redeem(loser,second));for(const user of [parent,guardian]){const v=(await view(user,'parent')).find(e=>e.school.id===s.id).school;assert.equal(v.students.length,1);assert.equal(v.students[0].id,t.id);assert.equal(v.invitations.length,0)}pass('separate invitations connect multiple guardians without duplicate students');
 const cross=fixtures[1],crossInvite=ok(await action(admin,'admin',cross.id,'createInvitation',{studentId:cross.students[1].id})).invitation;ok(await redeem(parent,crossInvite,cross.students[1].dob));assert.equal((await view(parent,'parent')).length,2);pass('one account connects children across isolated schools');
 const cancelled=ok(await action(admin,'admin',s.id,'createInvitation',{studentId:t.id})).invitation;let v=(await view(admin,'admin')).find(e=>e.school.id===s.id);const latest=v.school.invitations.at(-1);ok(await action(admin,'admin',s.id,'cancelInvitation',{id:latest.id}));assert.equal((await redeem(guardian,cancelled)).status,400);pass('cancelled invitation cannot grant access');
 const expired=ok(await action(admin,'admin',s.id,'createInvitation',{studentId:t.id})).invitation;let raw=await db.prepare('SELECT data FROM schools WHERE id=?').bind(s.id).first();let record=JSON.parse(raw.data);record.invitations.at(-1).expiresAt=Date.now()-1;await db.prepare('UPDATE schools SET data=? WHERE id=?').bind(JSON.stringify(record),s.id).run();assert.equal((await redeem(guardian,expired)).status,400);pass('expired invitation cannot grant access');
 const link=(await view(admin,'admin')).find(e=>e.school.id===s.id).school.links.find(l=>l.userId===parent.id);ok(await action(admin,'admin',s.id,'revokeGuardian',{id:link.id}));const revoked=(await view(parent,'parent')).find(e=>e.school.id===s.id);assert(!revoked||revoked.school.students.length===0);assert.equal((await view(guardian,'parent')).find(e=>e.school.id===s.id).school.students.length,1);pass('revocation removes only that guardian’s access immediately');
 const requester={id:'requester',email:'requester@example.com'},payload={studentName:'Unknown Child',dob:'2015-05-14',relationship:'Guardian',contactMobile:'9876543210'};ok(await action(requester,'parent',s.id,'requestChild',payload));assert.equal((await action(requester,'parent',s.id,'requestChild',payload)).status,400);const pv=(await view(requester,'parent'))[0].school;assert.equal(pv.students.length,0);assert.equal(pv.candidates.length,0);assert.equal(pv.notices.length,0);assert.equal(pv.requests[0].status,'Pending');pass('unmatched requests enter school-assisted review without private candidate matches or duplicate pending requests');
 ok(await action(admin,'admin',s.id,'reviewParent',{id:pv.requests[0].id,studentId:t.id,status:'Approved'}));let connected=(await view(requester,'parent'))[0].school;assert.equal(connected.students.length,1);assert(connected.notifications.some(n=>/approved/.test(n.title)));pass('school-assisted approval links verified selection and notifies the parent');
 assert.equal((await action(parent,'parent',s.id,'linkChild',{studentId:t.id,relationship:'Mother'})).status,400);assert.equal((await action(parent,'parent',s.id,'connectPhone',{studentName:'Known',dob:t.dob})).status,400);pass('legacy email and phone auto-link operations are disabled');
 const attacker={id:'guesser',email:'guesser@example.com'};for(let n=0;n<10;n++)assert.equal((await redeem(attacker,{code:'00000-00000-00000-00000'})).status,400);assert.equal((await redeem(attacker)).status,429);pass('failed connection attempts hit persistent server rate limit');
 ok(await action(team,'platform',s.id,'schoolStatus',{status:'Suspended'}));assert(!(await view(guardian,'parent')).some(e=>e.school.id===s.id));assert.equal((await action(admin,'admin',s.id,'createInvitation',{studentId:t.id})).status,400);pass('school suspension blocks parent records and new invitations');
 const suspended=(await view(admin,'admin')).find(e=>e.school.id===s.id).school;assert(suspended.audit.every(a=>!JSON.stringify(a).includes(invite.code.replaceAll('-',''))));pass('audit excludes invitation secrets');
 console.log(`${checks} enrollment and permission integration checks passed.`);
}finally{await mf.dispose()}
