import {getAppUser} from '../../../lib/auth/server';
import {firebaseConfigured,getStorageObject,putStorageObject} from '../../../lib/firebase/admin';
import {getSchool} from '../../../lib/school/firebase-store';
import {database,bucket} from '../../../lib/school/db';
import {actorFor,projectSchool,allowedClasses,check,uid,canDiscover,normalizeAttendance,type School,type Row} from '../../../lib/school/model';
export const dynamic='force-dynamic';
async function context(id:string,role:string){const u=await getAppUser();check(u,'Sign in to continue.');check(role!=='parent'||u.signInProvider==='google.com','Parents must use Continue with Google.');const row=firebaseConfigured()?await getSchool(id):await database().prepare('SELECT data FROM schools WHERE id = ?').bind(id).first<Row>();check(row,'School not found.');const s=normalizeAttendance(JSON.parse(row.data) as School);check(canDiscover(s,u)&&s.status==='Active','School is unavailable.');const a=actorFor(s,u,role);check(a.role===role,'You do not have access to this school.');return {s,a};}
export async function POST(req:Request){try{const origin=req.headers.get('origin');check(!origin||origin===new URL(req.url).origin,'Invalid origin.');const u=new URL(req.url);const {s,a}=await context(u.searchParams.get('schoolId')||'',u.searchParams.get('role')||'admin');const classId=u.searchParams.get('classId')||'';check((a.role==='admin'||a.role==='teacher')&&allowedClasses(s,a).includes(classId),'You cannot attach files to this class.');check(Number(req.headers.get('content-length')||0)<5500000,'File is too large.');const form=await req.formData();const f=form.get('file') as File;check(f&&typeof f.arrayBuffer==='function'&&f.size<=5*1024*1024,'Choose a file under 5 MB.');check(['application/pdf','image/jpeg','image/png','text/plain'].includes(f.type),'Use PDF, JPG, PNG or TXT files.');const bytes=new Uint8Array(await f.arrayBuffer());if(f.type==='image/png')check(bytes.length>8&&[137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v),'Invalid PNG image.');if(f.type==='image/jpeg')check(bytes[0]===255&&bytes[1]===216&&bytes[2]===255,'Invalid JPEG image.');if(f.type==='application/pdf')check(new TextDecoder().decode(bytes.slice(0,5))==='%PDF-','Invalid PDF file.');const key=`${s.id}/${classId}/${uid()}`;if(firebaseConfigured())await putStorageObject(key,bytes,f.type);else await bucket().put(key,bytes,{httpMetadata:{contentType:f.type},customMetadata:{name:f.name}});return Response.json({key,name:f.name,size:f.size,mimeType:f.type});}catch(e){return Response.json({error:(e as Error).message},{status:400});}}
export async function GET(req:Request){try{const u=new URL(req.url),key=u.searchParams.get('key')||'';const {s,a}=await context(key.split('/')[0],u.searchParams.get('role')||'admin');const visible=projectSchool(s,a);const homework=visible.homework.find(h=>h.attachment?.key===key);check(homework,'Attachment is not available to your account.');const attachment=homework.attachment;if(firebaseConfigured()){const f=await getStorageObject(key);check(f,'File not found.');const mime=attachment.mimeType||f.headers.get('content-type')||'application/octet-stream';return new Response(f.body,{headers:{'Content-Type':mime,'Content-Disposition':`${u.searchParams.get('inline')==='1'&&['image/jpeg','image/png'].includes(mime)?'inline':'attachment'}; filename="${(attachment.name||'attachment').replace(/[^a-zA-Z0-9._-]/g,'_')}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}const f=await bucket().get(key);check(f,'File not found.');return new Response(f.body,{headers:{'Content-Type':f.httpMetadata?.contentType||'application/octet-stream','Content-Disposition':`${u.searchParams.get('inline')==='1'&&['image/jpeg','image/png'].includes(f.httpMetadata?.contentType||'')?'inline':'attachment'}; filename="${(f.customMetadata?.name||'attachment').replace(/[^a-zA-Z0-9._-]/g,'_')}"`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}catch(e){return Response.json({error:(e as Error).message},{status:403});}}
