'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {fullName,type Row,type School} from '@/lib/school/model';
export function GuardianManagement({school:s,busy,action}:{school:School;busy:boolean;action:(name:string,payload?:Row,options?:Row)=>Promise<any>}){
 const [link,setLink]=useState(''),[copy,setCopy]=useState(''),[confirm,setConfirm]=useState<Row|null>(null);
 useEffect(()=>{setLink(`${location.origin}/?join=${encodeURIComponent(s.id)}`);setCopy('')},[s.id]);
 return <div className="guardian-panels"><section className="panel"><div className="panel-head"><div><h2>Parent Join link</h2><p>Share this same school link with all parents through WhatsApp, SMS, email or a school notice. Sharing is manual.</p></div></div><div className="guardian-form"><label>School Parent Join link<Input readOnly value={link} onFocus={e=>e.target.select()}/></label><Button disabled={!link} onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopy('Join link copied.')}catch{setCopy('Select the link above and copy it.')}}}>Copy Parent Join link</Button><p role="status">{copy}</p><p>Parents must use Continue with Google. Their email must match the student’s Parent Email, then their child’s DOB is verified. This link grants no access by itself.</p></div></section><section className="panel"><div className="panel-head"><h2>Guardian connections</h2></div>{s.links.length?s.links.map(l=><div className="guardian-row" key={l.id}><div><strong>{fullName(s.students.find(t=>t.id===l.studentId)||{})}</strong><p>{l.email||'Demo parent'} · {l.relationship||'Guardian'}</p>{!s.demo&&l.method!=='google-dob'&&<small>Needs verification through Parent Join</small>}</div><Button variant="outline" disabled={busy} onClick={()=>setConfirm({id:l.id})}>Revoke access</Button></div>):<p className="guardian-form">No guardians connected yet.</p>}</section><AlertDialog open={!!confirm} onOpenChange={v=>{if(!v)setConfirm(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Revoke guardian access?</AlertDialogTitle><AlertDialogDescription>This guardian will lose access to this child’s records and attachments immediately.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async()=>{await action('revokeGuardian',{id:confirm!.id});setConfirm(null)}}>Revoke access</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
}
