'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {formatPercent} from "@/lib/school/metrics";
import {today,type Row} from '@/lib/school/model';
function Choice({label,value,onChange,items}:{label:string;value:string;onChange:(v:string)=>void;items:{id:string;label:string}[]}){return <label>{label}<Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.id} value={i.id}>{i.label}</SelectItem>)}</SelectContent></Select></label>}
export function Reports({schoolId,yearId,role,yearStart,yearEnd}:{schoolId:string;yearId:string;role:string;yearStart?:string;yearEnd?:string}){
 const initial=today()<(yearStart||'')?yearStart!:today()>(yearEnd||'9999')?yearEnd!:today();
 const [period,setPeriod]=useState('daily'),[date,setDate]=useState(initial),[month,setMonth]=useState(initial.slice(0,7)),[classId,setClassId]=useState('all'),[division,setDivision]=useState('all'),[teacherId,setTeacherId]=useState('all'),[data,setData]=useState<Row|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');setData(null);const p=new URLSearchParams({schoolId,academicYearId:yearId,role,period,date,month});if(classId!=='all')p.set('classId',classId);if(division!=='all')p.set('division',division);if(teacherId!=='all')p.set('teacherId',teacherId);
 fetch('/api/reports?'+p,{signal:controller.signal}).then(async r=>{const result=await r.json() as Row;if(!r.ok)throw new Error(result.error||'Unable to load reports.');return result;}).then(result=>{if(!controller.signal.aborted)setData(result)}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort();
 },[schoolId,yearId,role,period,date,month,classId,division,teacherId,retry]);
 const [options,setOptions]=useState<Row>({classes:[],teachers:[]});useEffect(()=>{if(data)setOptions(data.options)},[data]);
 function exportCSV(){if(!data)return;const cells=[['Period',data.start,data.end],['Class','Division','Students','Present','Absent','Attendance %','Homework'],...data.rows.map((r:Row)=>[r.name,r.division,r.students,r.present,r.absent,r.percentage??'',r.homework])];const csv=cells.map(row=>row.map((v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'"+'$&').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`school-report-${data.start}-${data.end}.csv`;a.click();URL.revokeObjectURL(url);}
 return <section className="panel report-panel"><div className="panel-head"><div><h2>Daily & monthly reports</h2><p>Attendance and homework within your assigned scope.</p></div>{role!=='teacher'&&<Button variant="outline" disabled={busy||!data} onClick={exportCSV}>Export CSV</Button>}</div><div className="report-body"><div className="report-filters">
 <Choice label="Report Period" value={period} onChange={setPeriod} items={[{id:'daily',label:'Daily'},{id:'monthly',label:'Monthly'}]}/>
 {period==='daily'?<label>Date<Input type="date" value={date} min={yearStart} max={yearEnd} onChange={e=>setDate(e.target.value)}/></label>:<label>Month and year<Input type="month" value={month} min={yearStart?.slice(0,7)} max={yearEnd?.slice(0,7)} onChange={e=>setMonth(e.target.value)}/></label>}
 <Choice label={role==='teacher'?'Assigned class':'Class'} value={classId} onChange={v=>{setClassId(v);setDivision('all')}} items={[{id:'all',label:'All authorized classes'},...options.classes.map((c:Row)=>({id:c.id,label:c.name+' · '+c.division}))]}/>
 <Choice label="Division" value={division} onChange={setDivision} items={[{id:'all',label:'All divisions'},...Array.from(new Set<string>(options.classes.filter((c:Row)=>classId==='all'||c.id===classId).map((c:Row)=>c.division))).map(d=>({id:d,label:d}))]}/>
 {role!=='teacher'&&<Choice label="Teacher" value={teacherId} onChange={setTeacherId} items={[{id:'all',label:'All teachers'},...options.teachers.map((t:Row)=>({id:t.id,label:t.name}))]}/>}
 <Button variant="outline" onClick={()=>{setClassId('all');setDivision('all');setTeacherId('all')}}>Clear Filters</Button></div>
 {busy&&<p role="status">Loading report…</p>}{error&&<div role="alert" className="error-banner">{error} <Button variant="outline" onClick={()=>setRetry(x=>x+1)}>Retry</Button></div>}
 {data&&!busy&&<><p className="muted">{data.start} — {data.end}</p><div className="report-stats">{[['Total students',data.totals.students],['Present',data.totals.present],['Absent',data.totals.absent],['Attendance %',formatPercent(data.totals.percentage)],['Homework assigned',data.totals.homework]].map(([label,v])=><div key={label}><span>{label}</span><strong>{v}</strong></div>)}</div>
 {!data.rows.length?<p>No classes match these filters.</p>:<div className="report-table-wrap"><table><caption>Class and division breakdown</caption><thead><tr>{['Class','Division','Students','Present','Absent','Attendance %','Homework'].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{data.rows.map((r:Row)=><tr key={r.classId}><th scope="row">{r.name}</th><td>{r.division}</td><td>{r.students}</td><td>{r.present}</td><td>{r.absent}</td><td>{formatPercent(r.percentage)}</td><td>{r.homework}</td></tr>)}</tbody></table></div>}
 <p className="muted">Attendance = Present ÷ (Present + Absent). Unmarked days are excluded. Monthly totals count student-days. Active students are counted once per class enrollment; inactive or removed students are excluded. {teacherId!=='all'?'Attendance covers the selected teacher’s assigned classes; homework counts only that teacher’s assignments.':''}</p></>}
 </div></section>
}
